name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 min (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping Streamlit app (GET, follow redirects)
        run: |
          URL="https://olympicsvisualization4024.streamlit.app"   # <-- your URL
          echo "Pinging $URL at $(date -u)"

          # Random jitter so requests aren’t at the exact same second every run
          sleep $((RANDOM % 60))

          # GET (not HEAD), follow redirects (-L), fail on non-2xx, and read body to actually wake it
          # Also print status code & total time to the job summary.
          CODE=$(curl -sS -L --max-time 60 --retry 3 --retry-delay 5 \
                 -A "keepalive-bot/1.0" \
                 -o /dev/null -w "%{http_code}" "$URL")
          TIME=$(curl -sS -L --max-time 60 --retry 3 --retry-delay 5 \
                 -A "keepalive-bot/1.0" \
                 -o /dev/null -w "%{time_total}" "$URL")

          echo "HTTP code: $CODE  |  time: ${TIME}s"
          echo "HTTP code: $CODE  |  time: ${TIME}s" >> $GITHUB_STEP_SUMMARY

          # Fail the step if not 2xx
          if [[ ! "$CODE" =~ ^2 ]]; then
            echo "Non-2xx response; failing."
            exit 1
          fi
